### ISSUE TITLE
Per project sdk configuration

### ISSUE THREAD

**Issue by ctranxuan** [sdkman/sdkman-cli#683]
Please tick one:
- [X] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [ ] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:

Assume you have an environment managed with sdkman such as Java 11 by default, Maven 3.6.0 by default, etc.
But you have a project that requires Java 8 and Maven 3.5.3. It would be convenient if every-time you enter to the directory of the project, all your environment is setup with Java 8 and Maven 3.5.3 without having to settle it manually through multiple `sdk` command lines.

jenv.io has such nice feature (https://github.com/linux-china/jenv#jenvrc-support): it's addressed through a `jenvrc` file that contains the version of libraries we wish to customize. Then, you call a command `jenv init` that settles the right versions.

**Proposed feature:** being able to declare a `sdkmanrc` into a directory that would contain tools versions and a command `sdk init` that would set for the tools the versions declared in the file `sdkmanrc`

**Example:**
By default, we have java 11 and maven 3.6.0.
In the directory `my-project`, we have a `sdkmanrc` files that contains:

```
java=1.8.0_112
maven=3.5.3
```

Then doing:

```
cd my-project
sdk init
```

would setup the environment to java 1.8.0_112 and maven 3.5.3.

**Comment by marc0der** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Per project sdk configuration](https://trello.com/c/J3TlESvY/60-per-project-sdk-configuration)

**Comment by marc0der** [comment]
I would be keen on taking this a step further. How about we introduce a new top level `env` command. When you do an `sdk env init`, it will _create_ an `.sdkman` file in the current directory with all the current versions set in that shell.

Say you opened a shell and then used `sdk use` to set a different version of java, this new version of java (along with any other candidates and versions installed with sdkman already) will be written in this file. To recall the versions, a simple `sdk env` (or `sdk env load`) would `use` all of those in the current shell.

A proposal was also made by @EugenMayer that we add support for language specific descriptors like `.java-version` or `.gradle-version` etc. This should be simple to do, although the preferred method would still be to use an `.sdkman` file instead.

**Comment by lalloni** [comment]
So, how about instead of using an sdkman-specific config file, sdkman could use something that could be shared among similar tools so we can commit such file without cluttering projects with config files for multiple tools.

I'm thinking sdkman could just use the .tool-versions file that asdf uses. sdkman can use that file since is has a very simple format very similar to the proposed above; and it is not, at least in name or format, specific to any tool.

Think of this as what .editorconfig file has done as a standard way of configuring editor preferences for each project that can be read and honored by multiple editors/IDEs, to great benefit.

**Comment by marc0der** [comment]
Sounds like a great idea, although there is no harm in supporting both.

**Comment by helpermethod** [comment]
Hi @marc0der!

I would like to take a stab at this, as I think that functionality would be a great addition to SDKMAN.

I've already created a working SDKMAN extension which supports reading the environment settings from an `.sdkrc` file [here](https://github.com/helpermethod/sdkman-env).

**Comment by EugenMayer** [comment]
@helpermethod i would not go and reinvent the wheel in terms of file name. The standard is `.<language>-version`.

This holds for: rvm, npm, composer, jenv and pyenv

So i would really love to just stick to that instead of namespacing it. You usually will have exactly one ENV manager per language - and there are integrations on top of this already, like IntelliJ looks at some of those

**Comment by lalloni** [comment]
Again, as I said above, in case you missed it. I think that, ideally, this is a feature shouldn't be specific to this or any other tool but be usable across tools.
With that I mean is that instead of using an sdkman specific .sdkrc file we should aim to use something other tools already understand, like the .tool-versions file that asdf understands as well as other tools.
This standardization should benefit all tools and facilitate adoption from other tools like IDEs or editors.
While it would certainly benefit my teams by not needing to keep in sync the configuration files for all tools each project use, it while also avoid polluting the projects with configuration files for all the tools the different members of the team use. This is particularly applicable to open sources projects where there is great variance in what tools each developer use.

**Comment by helpermethod** [comment]
@Ialloni Agreed. I will change the extension to support `.tool-versions` instead.

**Comment by helpermethod** [comment]
@marc0der `.sdkman` or `.sdkrc`? It should be no problem supporting both but I would question if `.tools-version` wouldn't be enough?

Would result in less code, less things to test, and `.tools-version` seems to be familiar to users of `asdf-vm`.

I'll give it a try, though :).

**Comment by helpermethod** [comment]
So the extension now supports both formats.

But I wonder if the users of the `.tool-versions` won't run into any trouble when using both `sdkman` and `asdf` because we probably can't guarantee that both version managers are able to provide the same versions, no?

**Comment by helpermethod** [comment]
@marc0der The output leaves much to be desired (with just two entries).

![image](https://user-images.githubusercontent.com/1562019/75933907-65cacf80-5e7b-11ea-99f1-942bed5878bb.png)

Any ideas on how to cut down the logging output?

**Comment by helpermethod** [comment]
This is how the output with two entries looks (one for Java and one for Maven).

![image](https://user-images.githubusercontent.com/1562019/75936508-99f5be80-5e82-11ea-9488-02fe9dff5182.png)

**Comment by marc0der** [comment]
@helpermethod that looks great! Only supporting an sdkman descriptor does make most sense to me too tbh. I would call it .sdkman, as it is not an rc file in Unix parlance and also does not live in the user's home folder.

It would also be great to add some test for this new feature.

**Comment by EugenMayer** [comment]
`.*rc` files are like `.npmrc` rather have the character to be searched the tree up and not living in the home folder only ( IMHO ).

Depending on how this is understood, means "if no .sdkman then take the configuration from the home folder" this could be named `.*rc`.

I understand that this is about configuring more then just the java version and a like the idea - on the other hand i will miss the `.java-version` support way of doing this, since i expect developers to look for `.*-version` in their project ( for whatever language ) to understand what is required. But at least `.sdkman` / `.sdkrc` / `.tool-versions` or whatever you guys pick will have the same ( rather more ) capabilities, so maybe this is just convinience ( but convinience the IDE will understand ).

I expect e.g. IntelliJ to rather support `.java-version` then a specific `.<sometool>` since they are not interesting in understand "all the env to SDK tools out there" but rather "what version is expected, agnostig" - ave never seen `.tool-versions` yet, but that could just be me

**Comment by helpermethod** [comment]
@marc0der Because there is already a directory `.sdkman` in the HOME directory, I'd rather name the file `.sdkmanrc`.

This makes it clear for a user after checking out a project that this is a RC file for a tool called `sdkman`.

I agree that it goes against the original intent of `*-rc` files but nowadays these are pretty commonplace as a local configuration file (think `.bowerrc`, `.nvmrc`, `.jshintrc`) so the `*-rc` ending should be okay.

Another question:

Should the `sdk env` command just call `use`, or should it also `install` the missing tools?

Currently it checks the existence and installs them but I wonder if it would make sense to split these steps.

Something like 

`sdk env` -> just call `use` for each tool
`sdk env install` -> install the missing dependencies

**Comment by marc0der** [comment]
@helpermethod that makes perfect sense so let's go for `.sdkmanrc` then.

Regarding all the implementation details, how about we move to the cli-development slack channel to discuss it there?

**Comment by marc0der** [comment]
One outstanding bit we need to implement before closing this issue is config file generation using the env command.

**Comment by helpermethod** [comment]
Closing this issue as the last missing part has been fixed in #683.

**Comment by marcphilipp** [comment]
@helpermethod I think you forgot to actually click on "Close". 😉

**Comment by helpermethod** [comment]
@marcphilipp Thanks, now the PR is referenced instead of the issue.
@marc0der Can we close this, or do we need a release first?
